// GENERATED BY FLUTTERFIRE CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// 🔹 ANDROID
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEsQ6agTvKiZAgpHnnxMj0uaVC6ZaNzGg',
    appId: '1:600079573284:android:d91fce54b897ace77fd3b1',
    messagingSenderId: '600079573284',
    projectId: 'eduprep-academy',
    storageBucket: 'eduprep-academy.firebasestorage.app',
  );

  /// 🔹 iOS
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1o6wIYEZngNVJMi1IHQuUmyGcx_Ta3To',
    appId: '1:600079573284:ios:302714a2799653e27fd3b1',
    messagingSenderId: '600079573284',
    projectId: 'eduprep-academy',
    storageBucket: 'eduprep-academy.firebasestorage.app',
    iosBundleId: 'com.examsolving.eduPrepAcademy.ios',
  );
}
